export const randomText = [
    "The Eiffel Tower in Paris, France, is one of the most iconic structures in the world. Built in 1889 for the Exposition Universelle, it was initially criticized by many, but it quickly became a beloved symbol of French engineering and culture. Standing at over 300 meters tall, it offers a stunning view of the city. Millions of tourists visit it every year, climbing the stairs or taking the elevator to one of its three observation decks. At night, it is beautifully illuminated, making it a breathtaking sight from anywhere in the city.",
    
    "The Amazon rainforest is often called the 'lungs of the Earth' due to its vast size and role in producing oxygen. Spanning over nine countries in South America, it is home to an incredibly diverse range of species, both plant and animal. The forest is so dense and vast that many areas are still unexplored, and new species are regularly discovered. However, deforestation has become a serious issue in recent years, threatening not only the unique ecosystem but also the global climate, as the forest plays a critical role in regulating carbon dioxide levels in the atmosphere.",
    
    "Mount Everest, the highest mountain in the world, stands at a staggering 8,848 meters above sea level. Located in the Himalayas on the border between Nepal and China, it has been the ultimate challenge for mountaineers since it was first summited in 1953 by Sir Edmund Hillary and Tenzing Norgay. Despite modern climbing gear and technology, the journey to the summit remains perilous, with extreme cold, high winds, and a lack of oxygen at high altitudes. Hundreds of climbers attempt the ascent every year, but the dangers are real, and not all make it back safely.",
    
    "The Great Barrier Reef, located off the coast of Queensland, Australia, is the largest coral reef system in the world. It is composed of over 2,900 individual reefs and 900 islands, stretching for more than 2,300 kilometers. The reef is home to an astonishing variety of marine life, including more than 1,500 species of fish, 400 types of coral, and numerous species of sharks, rays, and marine mammals. Unfortunately, rising ocean temperatures and pollution have led to coral bleaching, putting the future of this natural wonder at risk. Conservation efforts are underway to protect and restore the reef.",
    
    "The Sahara Desert is the largest hot desert in the world, covering most of North Africa. Its vast, arid landscape consists of sand dunes, rocky plateaus, and oases, creating an environment that is both beautiful and harsh. Temperatures during the day can soar to over 50 degrees Celsius, while nights can be freezing. Despite its extreme conditions, the Sahara is home to a variety of animals and plants that have adapted to the challenging environment, such as camels, fennec foxes, and date palms. Nomadic tribes have also lived in the Sahara for centuries, mastering the art of survival in one of the most inhospitable places on Earth.",
    
    "The Northern Lights, also known as the Aurora Borealis, are one of the most spectacular natural light shows on Earth. They occur when charged particles from the sun interact with the Earth's magnetic field, causing vivid displays of color in the night sky. The best places to see the Northern Lights are in the Arctic regions, such as northern Norway, Sweden, Finland, Canada, and Alaska. The lights appear in shades of green, pink, purple, and blue, dancing across the sky in waves and curtains. For centuries, people have been mesmerized by this celestial phenomenon, and today, it attracts tourists from all over the world.",
    
    "The Galápagos Islands, located in the Pacific Ocean off the coast of Ecuador, are famous for their unique wildlife and their role in Charles Darwin's theory of evolution. The islands are home to many species that are found nowhere else in the world, such as the giant tortoise, marine iguana, and blue-footed booby. The isolation of the islands has allowed these species to evolve in ways that are distinctly different from their mainland counterparts. Today, the Galápagos Islands are a UNESCO World Heritage site and a popular destination for ecotourism, with strict conservation efforts in place to protect the fragile ecosystem.",
    
    "Venice, Italy, is known for its canals, gondolas, and beautiful architecture. Built on more than 100 small islands in a lagoon in the Adriatic Sea, Venice has no roads, only canals. The city's unique location and design have made it a UNESCO World Heritage site and a popular tourist destination. St. Mark's Square, the Grand Canal, and the Rialto Bridge are just a few of the city's many famous landmarks. However, Venice faces significant challenges, including rising sea levels and sinking foundations, which threaten its future. Efforts are underway to preserve this cultural and historical treasure.",
    
    "Chocolate is one of the most beloved treats in the world, enjoyed in countless forms, from bars and truffles to cakes and drinks. It originates from cacao beans, which were first cultivated by the ancient civilizations of Central and South America, such as the Aztecs and Mayans. They used cacao to make a bitter, spiced drink that was believed to have divine properties. Today, chocolate is sweetened and flavored in various ways, making it a global industry worth billions. Besides its delicious taste, chocolate also contains compounds that can improve mood and provide health benefits, though moderation is key.",
    
    "Whales are the largest animals on Earth, with some species, such as the blue whale, reaching lengths of up to 30 meters and weights of up to 200 tons. Despite their massive size, whales are gentle creatures that feed primarily on small organisms like krill and plankton. Whales are also known for their intelligence and complex social behaviors. Some species, such as humpback whales, are famous for their songs, which can be heard for miles underwater. Sadly, many whale species have been endangered due to hunting, pollution, and climate change. Conservation efforts are essential to protect these magnificent marine mammals.",
    
    "The Olympic Games are the world's foremost international sporting competition, held every four years. They bring together athletes from across the globe to compete in a wide range of sports, from track and field to swimming, gymnastics, and team sports like soccer and basketball. The first modern Olympic Games were held in Athens, Greece, in 1896, inspired by the ancient Olympic Games of Greece. Today, the Olympics are a symbol of international unity and excellence in sports, with both the Summer and Winter Games attracting millions of viewers worldwide. Athletes train for years for the chance to compete on this global stage.",
    
    "Dinosaurs roamed the Earth for over 160 million years, long before humans appeared. These prehistoric reptiles varied greatly in size and shape, from the massive, long-necked sauropods like Brachiosaurus to the fearsome, carnivorous Tyrannosaurus rex. Dinosaurs lived in diverse habitats, from forests to deserts, and their fossilized remains have been found on every continent. While some dinosaurs were gigantic, others were small and agile. Scientists believe that a mass extinction event, likely caused by an asteroid impact, led to the end of the dinosaurs about 65 million years ago. Today, their fossils offer a fascinating glimpse into the distant past.",
    
    "The Great Wall of China is one of the most impressive feats of engineering in human history. Stretching over 13,000 miles across northern China, it was built to protect Chinese states and empires from invasions by nomadic tribes. Construction began as early as the 7th century BC, and different dynasties added to it over the centuries. The wall is made of stone, brick, tamped earth, and other materials, and it runs through deserts, mountains, and plains. Despite its massive scale, the wall did not always succeed in keeping out invaders, but it remains a powerful symbol of China's strength and resilience.",
    
    "The moon landing in 1969 was one of the most significant achievements in human history. On July 20, astronaut Neil Armstrong became the first human to set foot on the moon, famously declaring, 'That's one small step for man, one giant leap for mankind.' The Apollo 11 mission, led by NASA, represented the culmination of years of work and the height of the Space Race between the United States and the Soviet Union. Armstrong, along with Buzz Aldrin and Michael Collins, made history as millions of people around the world watched the event on television. The moon landing remains a symbol of human curiosity and exploration.",
    
    "Bird migration is one of the most fascinating natural phenomena in the animal kingdom. Every year, millions of birds travel thousands of miles between their breeding and wintering grounds. Some species, like the Arctic Tern, make journeys that span the entire globe. Birds use a combination of environmental cues, such as the position of the sun, the Earth's magnetic field, and even their sense of smell, to navigate these long distances. Migration is essential for birds to find food and suitable habitats throughout the year. However, climate change and habitat destruction are posing increasing threats to migratory bird populations.",
    
    "The art of pottery has been practiced by human civilizations for thousands of years. From simple clay vessels to intricate ceramic sculptures, pottery has served both functional and decorative purposes throughout history. Ancient civilizations like the Egyptians, Greeks, and Chinese produced some of the most famous pottery, often using unique techniques to create beautiful and durable pieces. Pottery is made by shaping clay and then heating it in a kiln to harden the material. Modern pottery continues to thrive as an art form, with contemporary artists experimenting with new materials, glazes, and techniques to create innovative and striking works.",
    
    "The study of human evolution traces the origins of modern humans back millions of years. Early hominins, such as Australopithecus, lived in Africa around 4 million years ago. Over time, these early ancestors evolved into more advanced species, such as Homo habilis and Homo erectus, which began using tools and controlling fire. Eventually, Homo sapiens emerged, migrating out of Africa and spreading across the globe. Fossils and genetic studies have provided invaluable insights into the journey of human evolution, revealing a complex history of adaptation and survival. Understanding our evolutionary past helps us better understand the diversity and unity of humanity today.",
    
    "Volcanoes are among the most powerful and destructive forces in nature. They occur when molten rock, or magma, from beneath the Earth's crust rises to the surface. Eruptions can vary in intensity, from slow lava flows to massive explosions that spew ash and gas into the atmosphere. Some of the most famous volcanic eruptions in history include the destruction of Pompeii by Mount Vesuvius in 79 AD and the eruption of Mount St. Helens in 1980. Volcanoes are found all around the world, especially in the Pacific Ring of Fire. Despite their destructive power, volcanic soils are often very fertile, supporting agriculture in many regions.",
    
    "Bees are crucial to the survival of many ecosystems, as they play a key role in pollination. As they gather nectar from flowers, bees transfer pollen between plants, helping them reproduce. This process is essential for the production of fruits, vegetables, and other crops that humans rely on for food. Bees also produce honey, a natural sweetener that has been used by humans for thousands of years. However, bee populations have been declining in recent years due to factors such as pesticide use, habitat loss, and climate change. Protecting bees is essential for ensuring the health of our planet's ecosystems and food supply.",
    
    "Jazz music originated in the late 19th and early 20th centuries in African American communities in the southern United States, particularly in New Orleans. It is characterized by its use of improvisation, syncopated rhythms, and a strong sense of swing. Jazz has influenced countless other music genres, including blues, rock, and hip-hop, and it continues to be a vibrant and evolving art form. Some of the most famous jazz musicians include Louis Armstrong, Duke Ellington, and Miles Davis, whose innovative compositions and performances helped define the genre. Today, jazz festivals and concerts attract fans from all over the world.",
    
    "Sharks are one of the ocean's top predators, known for their sharp teeth and incredible hunting abilities. There are over 500 species of sharks, ranging from the massive whale shark, which feeds on plankton, to the small, elusive dwarf lantern shark. Despite their fearsome reputation, most sharks pose little threat to humans, and shark attacks are rare. Sharks play a crucial role in maintaining the balance of marine ecosystems by controlling the populations of other species. Unfortunately, many shark species are threatened by overfishing, habitat loss, and climate change. Conservation efforts are essential to protect these ancient and fascinating creatures.",
    
    "The human brain is one of the most complex and powerful organs in the body. It controls everything we do, from breathing and heart rate to thinking, feeling, and decision-making. The brain is made up of billions of neurons, which communicate with each other through electrical and chemical signals. Different parts of the brain are responsible for different functions, such as memory, movement, and language. Scientists are still uncovering the mysteries of how the brain works, and advances in neuroscience are helping us better understand conditions such as Alzheimer's disease, depression, and stroke. The brain's capacity for learning and adaptation is truly remarkable.",
    
    "The Mona Lisa, painted by Leonardo da Vinci, is one of the most famous and recognizable works of art in the world. The portrait of a woman with a mysterious smile has captivated audiences for centuries. Painted in the early 16th century, the Mona Lisa is housed in the Louvre Museum in Paris, where millions of visitors come to see it each year. The painting's fame is due not only to its artistic merit but also to the intrigue surrounding its subject and da Vinci's masterful technique. The use of sfumato, a technique of blending colors and tones, gives the Mona Lisa her enigmatic expression.",
    
    "The sport of soccer, also known as football in most countries, is the most popular sport in the world, with millions of fans and players on every continent. The game is simple: two teams of eleven players each try to score goals by kicking a ball into the opposing team's net. Soccer requires skill, endurance, and teamwork, and it is played at both amateur and professional levels. The FIFA World Cup, held every four years, is the most prestigious tournament in soccer, drawing billions of viewers. Iconic players like Pelé, Diego Maradona, and Lionel Messi have become global superstars through their performances on the field.",
    
    "The Titanic, one of the largest and most luxurious ships of its time, tragically sank on its maiden voyage in April 1912 after hitting an iceberg in the North Atlantic. Over 1,500 passengers and crew lost their lives in the disaster, making it one of the deadliest maritime tragedies in history. The sinking of the Titanic shocked the world and led to significant changes in safety regulations for ships, including the requirement for enough lifeboats for all passengers. The wreck of the Titanic was discovered in 1985, and it continues to be a subject of fascination and research.",
    
    "Rainforests are some of the most biologically diverse ecosystems on Earth, home to millions of species of plants, animals, and insects. Found in tropical regions near the equator, rainforests are known for their dense vegetation, towering trees, and frequent rainfall. The Amazon Rainforest, the largest in the world, plays a critical role in regulating the Earth's climate by absorbing large amounts of carbon dioxide. However, rainforests are under threat from deforestation, driven by logging, agriculture, and urban development. Protecting these vital ecosystems is crucial for preserving biodiversity and mitigating climate change.",
    
    "Pyramids, especially those in Egypt, are among the most enduring symbols of ancient civilizations. The Great Pyramid of Giza, built as a tomb for the Pharaoh Khufu, is one of the Seven Wonders of the Ancient World and the only one still standing. Constructed over 4,500 years ago, the pyramid's precise engineering and massive scale continue to awe researchers and visitors alike. While the pyramids were originally intended as burial sites for Egyptian royalty, they also served as symbols of the pharaohs' power and a gateway to the afterlife. Archaeologists are still uncovering new information about the construction and purpose of these incredible structures.",
    
    "The Grand Canyon, located in the state of Arizona in the United States, is one of the most stunning natural wonders in the world. Carved over millions of years by the Colorado River, the canyon is over a mile deep and stretches for 277 miles. Its layered rock formations reveal a rich geological history, dating back nearly two billion years. The Grand Canyon is not only a popular destination for tourists but also a site of cultural significance for Native American tribes. Hiking, rafting, and camping in and around the canyon offer visitors a chance to experience its breathtaking beauty up close.",
    
    "Mars, often called the 'Red Planet' due to its reddish appearance, has long been a subject of fascination for scientists and space enthusiasts alike. As the fourth planet from the sun, Mars is the most similar to Earth in terms of its atmosphere and potential to support life. In recent years, several missions, including NASA's Mars rovers, have been launched to explore the planet's surface and search for signs of past or present life. The possibility of human colonization of Mars has also been widely discussed, with space agencies and private companies like SpaceX working on technology that could make interplanetary travel a reality.",
    
    "The history of flight began with early attempts by humans to mimic birds, using wings and gliders in an effort to achieve powered flight. The breakthrough came in 1903 when the Wright brothers successfully flew the first powered airplane at Kitty Hawk, North Carolina. Since then, aviation has evolved rapidly, with airplanes becoming faster, larger, and more advanced. Commercial aviation has transformed global travel, allowing people to cross continents in a matter of hours. Today, aviation technology continues to advance, with innovations like supersonic jets and electric planes promising to shape the future of air travel."
  ];
  